---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/pi/jellyfin/library:/config
      - /external/Big/plex/tvseries:/data/PlexTvseries
      - /external/Big/plex/movies:/data/PlexMovies
      - /external/Big/Torrents/complete/movies:/data/TorrentMovies
      - /external/Big/Torrents/complete:/data/TorrentComplete
      - /external/Big/Torrents/complete/tvseries:/data/TorrentTvseries
      - /external/Big/Torrents/complete/Tv-series:/data/TorrentTv-Series
      - /external/Small/Torrent/complete:/data/TorrentComplete
      - /external/Small/Torrent/complete/Movies:/data/MoviesTorrent
      - /external/Small/Torrent/complete/tvseries:/data/tvshowsTorrent
      - /external/Small/Plex/Movies:/data/PlexSmallMovies
      - /external/Small/Plex/tv-series:/data/PlexSmallTvseries
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped


