---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
      - USER=pi #optional
      - PASS=pi #optional
        #- WHITELIST=iplist #optional
        #- HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ~/home/pi/trans/config:/config
      - /external/Big/Torrents:/downloads
      - /external/Big/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
